project:
  type: website
  output-dir: docs

website:
  title: "COTAN Datasets analysis"
  sidebar:
    background: "#D9E3E4"
    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Home
      - section: "Mouse Cortex Loo 2019"
        contents:
        - href: Dataset1.qmd
          text: "Cleaning and cell clustering"
        - href: geneCoexAnalysisDataset1.qmd
          text: "Coexpression analaysis"
          
      - section: "Mouse Cortex Yuzwa 2017"
        contents: 
        - href: CorticalCells_GSM2861511_E135-analysis.qmd
          text: "E13.5 Cleaning and cell clustering"
        - href: geneCoexAnalysisE13.5Yuzwa.qmd
          text: "Correlation analysis for E13.5"
        - href: CorticalCells_GSM2861514_E175-analysis.qmd
          text: "E17.5 Cleaning and cell clustering"
        - href: geneCoexAnalysisE17.5Yuzwa.qmd
          text: "Correlation analysis for E17.5"
          
      - section: "Mouse Brain "
      

format:
  html:
    theme: sketchy
    fontsize: 1em
    css: styles.css
    toc: true

editor: visual
execute: 
  freeze: auto
  warning: false
  

